import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const translations = {
  en: {
    home: 'Home',
    about: 'About',
    services: 'Service',
    contact: 'Contact',
    admin: 'Admin',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    switch_to_dark: 'Switch to Dark',
    switch_to_light: 'Switch to Light',
    profile: 'Profile',
    email: 'Email Address',
    password: 'Password',
    login_to_account: 'Login to your account',
    create_account: 'Create Account',
    already_have_account: 'Already have an account?',
    dont_have_account: "Don’t have an account?",
    // About page
    about_title: 'About MP Online Shop',
    about_intro: 'Welcome to MP Online Shop — your trusted platform for fast, secure, and reliable online services in Madhya Pradesh. From government documents to essential bill payments, we make everything simple, transparent, and efficient for you.',
    who_we_are: 'Who We Are',
    who_we_are_desc: 'MP Online Shop is a one-stop platform offering multiple online services such as:',
    list_pan: 'PAN & Aadhaar Card Application',
    list_bills: 'Bill Payments (Electricity, Water, Mobile Recharge)',
    list_forms: 'Online Form Filling',
    list_schemes: 'Government Scheme Applications',
    mission_title: 'Our Mission',
    mission_desc: 'To bridge the gap between citizens and government services by offering a seamless and hassle-free online experience, ensuring that every transaction is safe, secure, and completed in minutes.',
    contact_us: 'Contact Us',
    // Contact page
    get_in_touch: 'Get in Touch',
    get_in_touch_desc: 'Have questions or need help? We’re here for you. Contact us anytime and we’ll respond as quickly as possible.',
    phone_label: 'Phone',
    email_label: 'Email',
    // address_label kept below in ApplyForm section to avoid duplicates
    contact_form: 'Contact Form',
    full_name: 'Full Name',
    full_name_placeholder: 'Enter your full name',
    email_placeholder: 'Enter your email address',
    phone_placeholder: 'Enter your phone number',
    message: 'Message',
    message_placeholder: 'Write your message here...',
    send_message: 'Send Message',
    // Services page
    services_title_full: 'Our Services',
    services_intro: 'We offer a wide range of online services to make your life easier. From essential documents to daily bill payments — everything under one roof.',
    apply: 'Apply',
    apply_started: 'Apply started for',
    application_suffix: 'Application',
    // Use short title so header becomes "PAN Application"
    service_pan_title: 'PAN',
    service_pan_desc: 'Quick and hassle-free PAN card application & updates.',
    service_income_title: 'Income Certificate',
    service_income_desc: 'Get your income certificate issued with ease.',
    service_caste_title: 'Caste Certificate',
    service_caste_desc: 'Apply for caste certificate with complete guidance.',
    service_domicile_title: 'Domicile Certificate',
    service_domicile_desc: 'Proof of residence for official and legal purposes.',
    service_recharge_title: 'Mobile & DTH Recharge',
    service_recharge_desc: 'Fast and secure recharge for all major operators.',
    service_bills_title: 'Bill Payments',
    service_bills_desc: 'Pay electricity, water, and gas bills instantly.',
    service_property_title: 'Property Registration',
    service_property_desc: 'Hassle-free assistance for property registration.',
    service_formfill_title: 'Online Form Filling',
    service_formfill_desc: 'Apply for government schemes & forms online.',
    // Home slider
    home_slide1_title: 'PAN & Aadhaar Card Services',
    home_slide1_text: 'Apply for PAN or Aadhaar Card easily and quickly with our online services.',
    home_slide1_button: 'Apply Now',
    home_slide2_title: 'Online Money Transfer',
    home_slide2_text: 'Secure and fast online money transfer for your needs.',
    home_slide2_button: 'Send Money',
    home_slide3_title: 'All-in-One Online Services',
    home_slide3_text: 'From bill payments to document services, we’ve got you covered.',
    home_slide3_button: 'Explore Services',
    // ApplyForm
    applyform_fill_details: 'Fill the details below to start your application',
    fathers_name: "Father's Name",
    fathers_name_placeholder: "Enter father's name",
    mothers_name: "Mother's Name",
    mothers_name_placeholder: "Enter mother's name (optional)",
    dob: 'Date of Birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    income_amount: 'Income Amount (₹)',
    income_placeholder: 'Enter yearly income (min 35000)',
    aadhar_number: 'Aadhaar Number',
    aadhar_placeholder: '12-digit Aadhaar number',
    mobile_number: 'Mobile Number',
    mobile_placeholder: '10-digit mobile number',
    address_label: 'Address',
    address_placeholder: 'House no, Street, City, State, Pincode',
    samagra_id_label: 'Samagra ID Number',
    samagra_id_placeholder: '8-9 digit Samagra ID',
    cancel: 'Cancel',
    submit_application: 'Submit Application',
    submitting: 'Submitting...',
    please_fill_fields: 'Please fill all required fields',
    // UpdateForm & ViewForm
    update: 'Update',
    delete: 'Delete',
    my_pan_forms: 'My PAN Forms',
    no_pan_forms: 'No PAN forms found.',
    name_label_text: 'Name',
    mobile_label_text: 'Mobile',
    dob_label_text: 'DOB',
    delete_success: 'Deleted successfully!',
    delete_failed: 'Failed to delete',
    // NotFound
    notfound_text: 'Oops! Page not found.',
    back_home: 'Go Back Home',
    ghost_text: "It seems you've entered a ghost town 👻",
    // Admin
    admin_dashboard: 'Admin Dashboard',
    promote_user: 'Promote user to Admin',
    user_email: 'User email',
    make_admin: 'Make Admin',
    all_applications: 'All Applications (PAN + Income)',
    refresh: 'Refresh',
    loading: 'Loading...',
    no_forms: 'No forms found.',
    type_pan: 'PAN',
    type_income: 'Income',
    applicant: 'Applicant',
    submitted: 'Submitted',
    updated: 'Updated',
    contact_label_text: 'Contact',
    submitted_by: 'Submitted By',
    // Profile dropdown
    profile_dashboard: 'Dashboard',
    profile_my_profile: 'My Profile',
    profile_requested_services: 'Requested Services',
    profile_reviews: 'Reviews',
  },
  hi: {
    home: 'होम',
    about: 'हमारे बारे में',
    services: 'सेवाएं',
    contact: 'संपर्क',
    admin: 'एडमिन',
    login: 'लॉगिन',
    register: 'रजिस्टर',
    logout: 'लॉगआउट',
    switch_to_dark: 'डार्क मोड',
    switch_to_light: 'लाइट मोड',
    profile: 'प्रोफ़ाइल',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    login_to_account: 'अपने खाते में लॉगिन करें',
    create_account: 'खाता बनाएं',
    already_have_account: 'पहले से खाता है?',
    dont_have_account: 'खाता नहीं है?',
    // About page
    about_title: 'एमपी ऑनलाइन शॉप के बारे में',
    about_intro: 'एमपी ऑनलाइन शॉप में आपका स्वागत है — मध्य प्रदेश में तेज़, सुरक्षित और विश्वसनीय ऑनलाइन सेवाओं के लिए आपका विश्वसनीय प्लेटफॉर्म। सरकारी दस्तावेजों से लेकर आवश्यक बिल भुगतान तक, हम आपके लिए सब कुछ सरल, पारदर्शी और प्रभावी बनाते हैं।',
    who_we_are: 'हम कौन हैं',
    who_we_are_desc: 'एमपी ऑनलाइन शॉप एक ऐसा प्लेटफॉर्म है जहाँ आपको कई ऑनलाइन सेवाएँ एक ही जगह मिलती हैं:',
    list_pan: 'पैन और आधार कार्ड आवेदन',
    list_bills: 'बिल भुगतान (बिजली, पानी, मोबाइल रिचार्ज)',
    list_forms: 'ऑनलाइन फॉर्म भरना',
    list_schemes: 'सरकारी योजनाओं के आवेदन',
    mission_title: 'हमारा मिशन',
    mission_desc: 'नागरिकों और सरकारी सेवाओं के बीच की दूरी को कम करना — एक सहज और बिना झंझट वाले ऑनलाइन अनुभव के साथ, जिससे हर लेन-देन सुरक्षित, भरोसेमंद और मिनटों में पूरा हो।',
    contact_us: 'संपर्क करें',
    // Contact page
    get_in_touch: 'संपर्क करें',
    get_in_touch_desc: 'कोई सवाल है या मदद चाहिए? हम आपके लिए यहाँ हैं। कभी भी संपर्क करें, हम जल्द से जल्द जवाब देंगे।',
    phone_label: 'फ़ोन',
    email_label: 'ईमेल',
    // address_label kept below in ApplyForm section to avoid duplicates
    contact_form: 'संपर्क फॉर्म',
    full_name: 'पूरा नाम',
    full_name_placeholder: 'अपना पूरा नाम दर्ज करें',
    email_placeholder: 'अपना ईमेल पता दर्ज करें',
    phone_placeholder: 'अपना मोबाइल नंबर दर्ज करें',
    message: 'संदेश',
    message_placeholder: 'यहाँ अपना संदेश लिखें...',
    send_message: 'संदेश भेजें',
    // Services page
    services_title_full: 'हमारी सेवाएं',
    services_intro: 'हम आपके लिए कई ऑनलाइन सेवाएं प्रदान करते हैं। ज़रूरी दस्तावेज़ों से लेकर रोज़मर्रा के बिल भुगतान तक — सब कुछ एक ही जगह।',
    apply: 'आवेदन करें',
    apply_started: 'आवेदन शुरू किया गया',
    application_suffix: 'आवेदन',
    // Short title so header becomes "पैन आवेदन"
    service_pan_title: 'पैन',
    service_pan_desc: 'पैन कार्ड आवेदन और अपडेट — तेज़ और आसान।',
    service_income_title: 'आय प्रमाण पत्र',
    service_income_desc: 'अपना आय प्रमाण पत्र आसानी से प्राप्त करें।',
    service_caste_title: 'जाति प्रमाण पत्र',
    service_caste_desc: 'पूरी मार्गदर्शन के साथ जाति प्रमाण पत्र के लिए आवेदन करें।',
    service_domicile_title: 'स्थायी निवास प्रमाण पत्र',
    service_domicile_desc: 'आधिकारिक और कानूनी कार्यों के लिए निवास का प्रमाण।',
    service_recharge_title: 'मोबाइल और डीटीएच रिचार्ज',
    service_recharge_desc: 'सभी प्रमुख ऑपरेटरों के लिए तेज़ और सुरक्षित रिचार्ज।',
    service_bills_title: 'बिल भुगतान',
    service_bills_desc: 'बिजली, पानी और गैस के बिल तुरंत भरें।',
    service_property_title: 'सम्पत्ति पंजीकरण',
    service_property_desc: 'सम्पत्ति पंजीकरण के लिए बिना झंझट सहायता।',
    service_formfill_title: 'ऑनलाइन फॉर्म भरना',
    service_formfill_desc: 'सरकारी योजनाओं और फॉर्म के लिए ऑनलाइन आवेदन करें।',
    // Home slider
    home_slide1_title: 'पैन और आधार कार्ड सेवाएं',
    home_slide1_text: 'हमारी ऑनलाइन सेवाओं के साथ पैन या आधार कार्ड के लिए आसानी से और तेजी से आवेदन करें।',
    home_slide1_button: 'अभी आवेदन करें',
    home_slide2_title: 'ऑनलाइन मनी ट्रांसफर',
    home_slide2_text: 'आपकी जरूरतों के लिए सुरक्षित और तेज़ ऑनलाइन मनी ट्रांसफर।',
    home_slide2_button: 'पैसे भेजें',
    home_slide3_title: 'ऑल-इन-वन ऑनलाइन सेवाएं',
    home_slide3_text: 'बिल भुगतान से लेकर दस्तावेज़ सेवाओं तक, हम सब संभालते हैं।',
    home_slide3_button: 'सेवाएं देखें',
    // ApplyForm
    applyform_fill_details: 'अपना आवेदन शुरू करने के लिए नीचे विवरण भरें',
    fathers_name: 'पिता का नाम',
    fathers_name_placeholder: 'पिता का नाम दर्ज करें',
    mothers_name: 'माता का नाम',
    mothers_name_placeholder: 'माता का नाम दर्ज करें (वैकल्पिक)',
    dob: 'जन्म तिथि',
    gender: 'लिंग',
    male: 'पुरुष',
    female: 'महिला',
    other: 'अन्य',
    income_amount: 'आय राशि (₹)',
    income_placeholder: 'वार्षिक आय दर्ज करें (न्यूनतम 35000)',
    aadhar_number: 'आधार नंबर',
    aadhar_placeholder: '12 अंकों का आधार नंबर',
    mobile_number: 'मोबाइल नंबर',
    mobile_placeholder: '10 अंकों का मोबाइल नंबर',
    address_label: 'पता',
    address_placeholder: 'मकान नंबर, सड़क, शहर, राज्य, पिनकोड',
    samagra_id_label: 'समग्र आईडी नंबर',
    samagra_id_placeholder: '8-9 अंकों की समग्र आईडी',
    cancel: 'रद्द करें',
    submit_application: 'आवेदन जमा करें',
    submitting: 'जमा हो रहा है...',
    please_fill_fields: 'कृपया सभी आवश्यक फ़ील्ड भरें',
    // UpdateForm & ViewForm
    update: 'अपडेट',
    delete: 'हटाएं',
    my_pan_forms: 'मेरे पैन फॉर्म',
    no_pan_forms: 'कोई पैन फॉर्म नहीं मिला।',
    name_label_text: 'नाम',
    mobile_label_text: 'मोबाइल',
    dob_label_text: 'ज.तिथि',
    delete_success: 'सफलतापूर्वक हटाया गया!',
    delete_failed: 'हटाने में विफल',
    // NotFound
    notfound_text: 'ओह! पेज नहीं मिला।',
    back_home: 'होम पेज पर जाएँ',
    ghost_text: 'लगता है आप भूतिया शहर में आ गए हैं 👻',
    // Admin
    admin_dashboard: 'एडमिन डैशबोर्ड',
    promote_user: 'यूज़र को एडमिन बनाएं',
    user_email: 'यूज़र ईमेल',
    make_admin: 'एडमिन बनाएं',
    all_applications: 'सभी आवेदन (पैन + आय प्रमाण पत्र)',
    refresh: 'रीफ़्रेश',
    loading: 'लोड हो रहा है...',
    no_forms: 'कोई फॉर्म नहीं मिला।',
    type_pan: 'पैन',
    type_income: 'आय',
    applicant: 'आवेदक',
    submitted: 'जमा किया गया',
    updated: 'अपडेट किया गया',
    contact_label_text: 'संपर्क',
    submitted_by: 'द्वारा जमा',
    // Profile dropdown
    profile_dashboard: 'डैशबोर्ड',
    profile_my_profile: 'मेरा प्रोफ़ाइल',
    profile_requested_services: 'अनुरोधित सेवाएँ',
    profile_reviews: 'समीक्षाएँ',
  },
};

export const LanguageContext = createContext({
  lang: 'en',
  setLang: () => {},
  toggleLang: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');
  const toggleLang = () => setLang((l) => (l === 'en' ? 'hi' : 'en'));

  useEffect(() => {
    localStorage.setItem('lang', lang);
    // Update <html lang="..."> for accessibility
    try {
      document.documentElement.setAttribute('lang', lang);
    } catch {}
  }, [lang]);

  const t = useMemo(() => {
    const dict = translations[lang] || translations.en;
    return (key) => dict[key] ?? key;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, toggleLang, t }), [lang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
